### ISSUE TITLE
ask for training dataset

### ISSUE THREAD

**Issue by hmep313** [yangqy1110/MGDM#5]
hi,excellent work!
When I tried to reproducing I was confused about dataset.In experiment about BreastMnist you mentioned ''The images are categorized into three classes, which are normal,benign, and malignant. The model was then tested with 218 normal images, 105 benign, and 66 malignant images. Taking into account the balanced distribution of classes in this dataset, we augmented images to ensure 250 per category.''
Can you provide some details on this like how can I prepare the dataset?

**Comment by yangqy1110** [comment]
Hello, thank you for your attention. The data can be simply resized as shown in TABLE 1. We apologize for any misunderstanding. What we intended to convey is that we added 32, 145, and 184 images respectively using the trained diffusion, so that each category in the final training set has 250 images.

**Comment by hmep313** [comment]
thank you so much!
